using NpgsqlTypes;
using Pgvector;

namespace MeetUp.Api.Entities;

/// <summary>
/// A searchable slice of a transcript. Chunks are built from whole utterances rather than by
/// slicing raw text, so every chunk keeps real start/end timestamps and search results can jump
/// straight to the moment in the recording.
/// </summary>
public class TranscriptChunk
{
    public Guid Id { get; set; }

    public Guid MeetingId { get; set; }
    public Meeting? Meeting { get; set; }

    public Guid TranscriptId { get; set; }
    public Transcript? Transcript { get; set; }

    public string Text { get; set; } = string.Empty;

    public int StartMs { get; set; }
    public int EndMs { get; set; }

    /// <summary>768-dimension Gemini embedding (AiProviders:EmbeddingModel). Null until the embedding job runs.</summary>
    public Vector? Embedding { get; set; }

    /// <summary>
    /// Generated by PostgreSQL from <see cref="Text"/> — never assigned in code. Backs the keyword
    /// arm of search so both arms work at chunk granularity.
    /// </summary>
    public NpgsqlTsVector? SearchVector { get; set; }
}
